sudo: false
language: node_js
node_js: 
  - '4.5'
before_install:
# Get installer script.
  - cd bin
  - wget https://github.com/nodeGame/nodegame/raw/master/bin/install-nodegame-for-module.sh
  - chmod a+x install-nodegame-for-module.sh
  - cd ..
# Make dependencies available for prisoner.
  - mkdir nodegame
  - ln -s nodegame/node_modules .
install:
# Get nodegame.
  - ./bin/install-nodegame-for-module.sh -n "smoosh ya-csv"
# Install dependencies.
  - npm install
# Register this prisoner game in nodegame.
  - ln -s ../.. nodegame/games/prisoner
script:
# Run autoplay-game to get memory dump.
  - cd nodegame
  - node test/launcher-autoplay.js prisoner
  - cd ..
# Run tests on dump.
  - npm test
