language: node_js
node_js: 0.10
install:
# Get nodegame.
  - bin/install-nodegame-for-ultimatum.sh
# Install dependencies.
  - npm install
script:
# Run autoplay-game to get memory dump.
  - cd nodegame
  - node ../test/launcher-autoplay.js
  - cd ..
# Run tests on dump.
  - npm test
